### ISSUE TITLE
Port NAC Huginn to Ruby

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-nac#2]
NAC - National Arts Centre -  http://nac-cna.ca

Artifact: nac-events

Old Huginn: https://huginn-staging.herokuapp.com/scenarios/3

The site map to load for NAC is here http://nac-cna.ca/en/site/sitemap

All the URLs that have https://nac-cna.ca/en/event/ should be crawled. For example, there are about 288 webpage URLs at the moment.

**Comment by saumier** [comment]
@gregory - I will add more notes here to guide Dev.

**Comment by saumier** [comment]
@dev-aravind The site map to load for NAC is here `http://nac-cna.ca/en/site/sitemap`

All the URLs that have `https://nac-cna.ca/en/event/` should be crawled. For example, there are about 288 webpage URLs at the moment.

**Comment by dev-aravind** [comment]
@saumier I've updated the code scrape using the sitemap. Please refer [this PR](https://github.com/culturecreates/artsdata-planet-nac/pull/3)

**Comment by saumier** [comment]
@dev-aravind I linked your PR to this issue. Please link your PRs to issues when you work on the issue.

**Comment by dev-aravind** [comment]
@saumier The fixes you mentioned are in the PR that is linked to this issue.

**Comment by dev-aravind** [comment]
Assignning this back to @dev-aravind as we are missing the date type in the NAC events data.

**Comment by dev-aravind** [comment]
@saumier There seems to be an error in the RDF data on NAC website.

https://validator.schema.org/#url=https%3A%2F%2Fnac-cna.ca%2Fen%2Fevent%2F35390
