### ISSUE TITLE
Organizers missing name

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-nac#6]
There are many organizations that are related to events through the schema:organizer property. But most Organizations are missing a name (mandatory) and should ideally have a sameAs.  This is triggering a SHACL validation error.

**Comment by saumier** [comment]
@dev-aravind Can you remove the event organizations that have no name from the data sent to Artsdata. I will take care of asking NAC to make the change to their JSON-LD.

**Comment by dev-aravind** [comment]
@saumier This is fixed in [Artsdata](https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20nac-events&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-nac/nac-events) right now. Please test it out and let me know if you see any issues.

**Comment by saumier** [comment]
@dev-aravind The organizers with blank names are removed, however, the organizers that have names are also removed.

This event has an organizer that has a name and should not be removed:
https://kg.artsdata.ca/en/entity?uri=https%3A%2F%2Fnac-cna.ca%2Fen%2Fevent%2F35975%232025-05-04T15%3A00%3A00-04%3A00

If you click the dereference link in Nebula, you can see that the JSON-LD on the webpage has an organizer `https://nac-cna.ca/en/theatrefrancais` that should remain. So in Artsdata this event should end up with 2 organizers: the one from the webpage and the one we add by default in the pipeline.

**Comment by dev-aravind** [comment]
@saumier [This](https://raw.githubusercontent.com/culturecreates/artsdata-planet-nac/cbebb38450ea09b10672e880efe556bd582af87a/output/entities.jsonld) is a raw file from an import before the remove organizations SPARQL was added. I did not find any organization for that particular event in this. Can you please double check this?

Update: The organization issue is fixed now. Please check the same event that you mentioned in the previous comment to verify the event. Thanks.

**Comment by saumier** [comment]
@dev-aravind You nailed it. Perfect. I'm closing this issue. Thx.
